const CACHE='caseirinho-loja-v8.10.2-production-stability';
const PATCH='./storefront-stability-v8-10-2.js';
const SHELL=['./','./index.html','./manifest.webmanifest','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png','./icons/apple-touch-icon.png',PATCH];
async function cacheShell(){const c=await caches.open(CACHE);for(const url of SHELL){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await c.put(url,r.clone())}catch(_){}}}
async function injectPatch(r){if(!r)return r;const ct=r.headers.get('content-type')||'';if(!ct.includes('text/html'))return r;let html=await r.text();if(!html.includes('storefront-stability-v8-10-2.js'))html=html.replace(/<\/body>/i,'<script src="./storefront-stability-v8-10-2.js?v=20260909"></script></body>');const h=new Headers(r.headers);h.delete('content-length');return new Response(html,{status:r.status,statusText:r.statusText,headers:h})}
self.addEventListener('install',e=>e.waitUntil(cacheShell().then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(/john-cloud-api-production\.up\.railway\.app/.test(u.host))return;if(e.request.method!=='GET')return;if(e.request.mode==='navigate'){e.respondWith((async()=>{try{const net=await fetch(e.request,{cache:'no-store'});const out=await injectPatch(net);if(out&&out.ok)caches.open(CACHE).then(c=>c.put('./index.html',out.clone())).catch(()=>{});return out}catch(_){const cached=await caches.match('./index.html');return injectPatch(cached)}})());return}e.respondWith(caches.match(e.request).then(cached=>cached||fetch(e.request).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone())).catch(()=>{});return r})))});
